name: Build Documentation

on:
  push:
    workflow_dispatch:
    pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Standard drop-in approach that should work for most people.

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements.txt

    - name: Check installation
      run: |
        which python
        python -c "import cot"
    # Build docs
    - name: Generate HTML docs
      uses: rickstaa/sphinx-action@master
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: docs/_build/html/

deploy:
  - name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Documentation
        uses: actions/download-artifact@v2
        with:
          name: Documentation
      
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          user_name: "kaiyiz"
          user_email: "kaiyizhang0809@gmail.com"